name: Update LcInstaller Source

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update_json.py
        run: python update_json.py

      - name: Commit & push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add source.json
          git diff --staged --quiet || git commit -m "Update LcInstaller source"
          git push
